en:
    view: 'View'
    editor: 'Editor'
    editInWindow: 'Window'
    editInPanel: 'Panel'
    viewNormal: 'Normal'
    viewFull: 'Full width only'
    viewTitle: 'Adjusting browsing panel'
    editorTitle: 'Adjusting editor panel or window'
    editInWindowTitle: 'Editor will be opened in a popup window'
    editInPanelTitle: 'Editor will appear inside a page'
    viewNormalTitle: 'Map panel will have "fullscreen" button'
    viewFullTitle: 'Map panel will always have maximum size'
    growTitle: 'Click to grow the panel'
    shrinkTitle: 'Click to shrink the panel'
    zoomInTitle: 'Zoom in'
    zoomOutTitle: 'Zoom out'
    selectLayer: 'Select layer'
    addLayer: 'Add layer'
    keyNeeded: 'This layer needs a developer key (<a href="%s" target="devkey">how to get it</a>)'
    keyNeededAlert: 'This layer needs a developer key'
